-- MySQL Script generated by MySQL Workbench
-- dom 09 may 2021 23:03:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema modelo_repartos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema modelo_repartos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modelo_repartos` ;
USE `modelo_repartos` ;

-- -----------------------------------------------------
-- Table `modelo_repartos`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_repartos`.`ciudad` (
  `nombre-ciudad` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`nombre-ciudad`),
  UNIQUE INDEX `nombre-ciudad_UNIQUE` (`nombre-ciudad` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_repartos`.`delegacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_repartos`.`delegacion` (
  `nombre-delegacion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NULL,
  `nombre-ciudad` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre-delegacion`),
  UNIQUE INDEX `nombre-delegacion_UNIQUE` (`nombre-delegacion` ASC) VISIBLE,
  INDEX `fk_delegacion_ciudad_idx` (`nombre-ciudad` ASC) VISIBLE,
  CONSTRAINT `fk_delegacion_ciudad`
    FOREIGN KEY (`nombre-ciudad`)
    REFERENCES `modelo_repartos`.`ciudad` (`nombre-ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_repartos`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_repartos`.`empleado` (
  `codigo-empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `telefono` VARCHAR(20) NULL,
  `anio_nacimiento` DATE NULL,
  PRIMARY KEY (`codigo-empleado`),
  UNIQUE INDEX `codigo-empleado_UNIQUE` (`codigo-empleado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_repartos`.`conductor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_repartos`.`conductor` (
  `codigo-empleado` INT NOT NULL,
  `anio-carnet` DATE NULL,
  `tipo-carnet` VARCHAR(20) NULL,
  PRIMARY KEY (`codigo-empleado`),
  UNIQUE INDEX `codigo-empleado_UNIQUE` (`codigo-empleado` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_conductor`
    FOREIGN KEY (`codigo-empleado`)
    REFERENCES `modelo_repartos`.`empleado` (`codigo-empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_repartos`.`administrativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_repartos`.`administrativo` (
  `codigo-empleado` INT NOT NULL,
  `nivel-estudios` INT NULL,
  PRIMARY KEY (`codigo-empleado`),
  UNIQUE INDEX `codigo-empleado_UNIQUE` (`codigo-empleado` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_administrativo`
    FOREIGN KEY (`codigo-empleado`)
    REFERENCES `modelo_repartos`.`empleado` (`codigo-empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_repartos`.`camion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_repartos`.`camion` (
  `codigo-camion` INT NOT NULL,
  `matricula` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `tara` INT NULL,
  PRIMARY KEY (`codigo-camion`),
  UNIQUE INDEX `codigo-camion_UNIQUE` (`codigo-camion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_repartos`.`viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_repartos`.`viaje` (
  `nombre-delegacion` VARCHAR(45) NOT NULL,
  `codigo-viaje` INT NOT NULL,
  `codigo-camion` INT NULL,
  PRIMARY KEY (`nombre-delegacion`, `codigo-viaje`),
  INDEX `fk_camion_viaje_idx` (`codigo-camion` ASC) VISIBLE,
  UNIQUE INDEX `codigo-viaje_UNIQUE` (`codigo-viaje` ASC) VISIBLE,
  UNIQUE INDEX `nombre-delegacion_UNIQUE` (`nombre-delegacion` ASC) VISIBLE,
  CONSTRAINT `fk_delegacion_viaje`
    FOREIGN KEY (`nombre-delegacion`)
    REFERENCES `modelo_repartos`.`delegacion` (`nombre-delegacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_camion_viaje`
    FOREIGN KEY (`codigo-camion`)
    REFERENCES `modelo_repartos`.`camion` (`codigo-camion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_repartos`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_repartos`.`cliente` (
  `codigo-cliente` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `telefono-contacto` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo-cliente`),
  UNIQUE INDEX `codigo-cliente_UNIQUE` (`codigo-cliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_repartos`.`asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_repartos`.`asignacion` (
  `codigo-empleado` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `nombre-delegacion` VARCHAR(45) NULL,
  `fecha-fin` DATE NULL,
  PRIMARY KEY (`codigo-empleado`, `fecha`),
  UNIQUE INDEX `codigo-empleado_UNIQUE` (`codigo-empleado` ASC) VISIBLE,
  INDEX `fk_delegacion_asignacion_idx` (`nombre-delegacion` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_asignacion`
    FOREIGN KEY (`codigo-empleado`)
    REFERENCES `modelo_repartos`.`empleado` (`codigo-empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_delegacion_asignacion`
    FOREIGN KEY (`nombre-delegacion`)
    REFERENCES `modelo_repartos`.`delegacion` (`nombre-delegacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_repartos`.`conduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_repartos`.`conduccion` (
  `codigo-empleado` INT NOT NULL,
  `nombre-delegacion` VARCHAR(45) NOT NULL,
  `codigo-viaje` INT NOT NULL,
  `importe-dietas` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo-empleado`, `nombre-delegacion`, `codigo-viaje`),
  UNIQUE INDEX `codigo-empleado_UNIQUE` (`codigo-empleado` ASC) VISIBLE,
  INDEX `fk_viaje_conduccion_idx` (`codigo-viaje` ASC, `nombre-delegacion` ASC) VISIBLE,
  UNIQUE INDEX `nombre-delegacion_UNIQUE` (`nombre-delegacion` ASC) VISIBLE,
  CONSTRAINT `fk_conductor_conduccion`
    FOREIGN KEY (`codigo-empleado`)
    REFERENCES `modelo_repartos`.`conductor` (`codigo-empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viaje_conduccion`
    FOREIGN KEY (`codigo-viaje` , `nombre-delegacion`)
    REFERENCES `modelo_repartos`.`viaje` (`codigo-viaje` , `nombre-delegacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_repartos`.`recorrido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_repartos`.`recorrido` (
  `nombre-ciudad` VARCHAR(45) NOT NULL,
  `nombre-delegacion` VARCHAR(45) NOT NULL,
  `codigo-viaje` INT NOT NULL,
  `fecha-hora` DATETIME NULL,
  PRIMARY KEY (`nombre-ciudad`, `nombre-delegacion`, `codigo-viaje`),
  INDEX `fk_viaje_recorrido_idx` (`nombre-delegacion` ASC, `codigo-viaje` ASC) VISIBLE,
  UNIQUE INDEX `nombre-ciudad_UNIQUE` (`nombre-ciudad` ASC) VISIBLE,
  UNIQUE INDEX `nombre-delegacion_UNIQUE` (`nombre-delegacion` ASC) VISIBLE,
  UNIQUE INDEX `codigo-viaje_UNIQUE` (`codigo-viaje` ASC) VISIBLE,
  CONSTRAINT `fk_ciudad_recorrido`
    FOREIGN KEY (`nombre-ciudad`)
    REFERENCES `modelo_repartos`.`ciudad` (`nombre-ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viaje_recorrido`
    FOREIGN KEY (`nombre-delegacion` , `codigo-viaje`)
    REFERENCES `modelo_repartos`.`viaje` (`nombre-delegacion` , `codigo-viaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo_repartos`.`reparto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelo_repartos`.`reparto` (
  `nombre-ciudad` VARCHAR(45) NOT NULL,
  `nombre-delegacion` VARCHAR(45) NOT NULL,
  `codigo-viaje` INT NOT NULL,
  `codigo-cliente` INT NOT NULL,
  `paquetes-cargados` INT NULL,
  `paquetes-descargados` INT NULL,
  PRIMARY KEY (`nombre-ciudad`, `nombre-delegacion`, `codigo-viaje`, `codigo-cliente`),
  INDEX `fk_cliente_reparto_idx` (`codigo-cliente` ASC) VISIBLE,
  UNIQUE INDEX `nombre-ciudad_UNIQUE` (`nombre-ciudad` ASC) VISIBLE,
  UNIQUE INDEX `nombre-delegacion_UNIQUE` (`nombre-delegacion` ASC) VISIBLE,
  UNIQUE INDEX `codigo-viaje_UNIQUE` (`codigo-viaje` ASC) VISIBLE,
  UNIQUE INDEX `codigo-cliente_UNIQUE` (`codigo-cliente` ASC) VISIBLE,
  CONSTRAINT `fk_recorrido_reparto`
    FOREIGN KEY (`nombre-ciudad` , `nombre-delegacion` , `codigo-viaje`)
    REFERENCES `modelo_repartos`.`recorrido` (`nombre-ciudad` , `nombre-delegacion` , `codigo-viaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_reparto`
    FOREIGN KEY (`codigo-cliente`)
    REFERENCES `modelo_repartos`.`cliente` (`codigo-cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
