-- MySQL Script generated by MySQL Workbench
-- lun 10 may 2021 07:38:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inmobiliario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inmobiliario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inmobiliario` ;
USE `inmobiliario` ;

-- -----------------------------------------------------
-- Table `inmobiliario`.`poblacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inmobiliario`.`poblacion` (
  `nombre-pobl` VARCHAR(45) NOT NULL,
  `numero-habitantes` INT NULL,
  PRIMARY KEY (`nombre-pobl`),
  UNIQUE INDEX `nombre-pobl_UNIQUE` (`nombre-pobl` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliario`.`zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inmobiliario`.`zona` (
  `nombre-pobl` VARCHAR(45) NOT NULL,
  `nombre-zona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre-pobl`, `nombre-zona`),
  UNIQUE INDEX `nombre-pobl_UNIQUE` (`nombre-pobl` ASC) VISIBLE,
  UNIQUE INDEX `nombre-zona_UNIQUE` (`nombre-zona` ASC) VISIBLE,
  CONSTRAINT `fk_poblacion_zona`
    FOREIGN KEY (`nombre-pobl`)
    REFERENCES `inmobiliario`.`poblacion` (`nombre-pobl`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliario`.`piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inmobiliario`.`piso` (
  `codigo-piso` INT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `superficie` INT NULL,
  `numero-habitantes` INT NULL,
  `precio` INT NULL,
  `nombre-pobl` VARCHAR(45) NULL,
  `nombre-zona` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo-piso`),
  UNIQUE INDEX `codigo-piso_UNIQUE` (`codigo-piso` ASC) VISIBLE,
  INDEX `fk_zona_piso_idx` (`nombre-pobl` ASC, `nombre-zona` ASC) VISIBLE,
  CONSTRAINT `fk_zona_piso`
    FOREIGN KEY (`nombre-pobl` , `nombre-zona`)
    REFERENCES `inmobiliario`.`zona` (`nombre-pobl` , `nombre-zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliario`.`caracteristica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inmobiliario`.`caracteristica` (
  `codigo-caracteristica` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo-caracteristica`),
  UNIQUE INDEX `codigo-caracteristica_UNIQUE` (`codigo-caracteristica` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliario`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inmobiliario`.`persona` (
  `codigo-persona` INT NOT NULL COMMENT '	',
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo-persona`),
  UNIQUE INDEX `codigo-persona_UNIQUE` (`codigo-persona` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliario`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inmobiliario`.`vendedor` (
  `codigo-persona` INT NOT NULL,
  `nss` VARCHAR(45) NULL,
  `sueldo` INT NULL,
  PRIMARY KEY (`codigo-persona`),
  UNIQUE INDEX `codigo-persona_UNIQUE` (`codigo-persona` ASC) VISIBLE,
  CONSTRAINT `fk_persona_vendedor`
    FOREIGN KEY (`codigo-persona`)
    REFERENCES `inmobiliario`.`persona` (`codigo-persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliario`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inmobiliario`.`cliente` (
  `codigo-persona` INT NOT NULL,
  PRIMARY KEY (`codigo-persona`),
  UNIQUE INDEX `codigo-persona_UNIQUE` (`codigo-persona` ASC) VISIBLE,
  CONSTRAINT `fk_persona_cliente`
    FOREIGN KEY (`codigo-persona`)
    REFERENCES `inmobiliario`.`persona` (`codigo-persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliario`.`propietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inmobiliario`.`propietario` (
  `codigo-persona` INT NOT NULL,
  `nif` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo-persona`),
  UNIQUE INDEX `codigo-persona_UNIQUE` (`codigo-persona` ASC) VISIBLE,
  CONSTRAINT `fk_persona_propietario`
    FOREIGN KEY (`codigo-persona`)
    REFERENCES `inmobiliario`.`persona` (`codigo-persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliario`.`asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inmobiliario`.`asignacion` (
  `codigo-cliente` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `codigo-vendedor` INT NULL,
  `fecha-fin` DATE NULL,
  PRIMARY KEY (`codigo-cliente`, `fecha`),
  UNIQUE INDEX `codigo-cliente_UNIQUE` (`codigo-cliente` ASC) VISIBLE,
  INDEX `fk_vendedor_asignacion_idx` (`codigo-vendedor` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_asignacion`
    FOREIGN KEY (`codigo-cliente`)
    REFERENCES `inmobiliario`.`cliente` (`codigo-persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendedor_asignacion`
    FOREIGN KEY (`codigo-vendedor`)
    REFERENCES `inmobiliario`.`vendedor` (`codigo-persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliario`.`preferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inmobiliario`.`preferencia` (
  `codigo-persona` INT NOT NULL,
  `nombre-pobl` VARCHAR(45) NOT NULL,
  `nombre-zona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo-persona`, `nombre-pobl`, `nombre-zona`),
  UNIQUE INDEX `codigo-persona_UNIQUE` (`codigo-persona` ASC) VISIBLE,
  INDEX `fk_zona_preferencia_idx` (`nombre-pobl` ASC, `nombre-zona` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_preferencia`
    FOREIGN KEY (`codigo-persona`)
    REFERENCES `inmobiliario`.`cliente` (`codigo-persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zona_preferencia`
    FOREIGN KEY (`nombre-pobl` , `nombre-zona`)
    REFERENCES `inmobiliario`.`zona` (`nombre-pobl` , `nombre-zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliario`.`satisfaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inmobiliario`.`satisfaccion` (
  `codigo-piso` INT NOT NULL,
  `codigo-caracteristica` INT NOT NULL,
  `satisface` TINYINT NULL,
  PRIMARY KEY (`codigo-piso`, `codigo-caracteristica`),
  UNIQUE INDEX `codigo-piso_UNIQUE` (`codigo-piso` ASC) VISIBLE,
  UNIQUE INDEX `codigo-caracteristica_UNIQUE` (`codigo-caracteristica` ASC) VISIBLE,
  CONSTRAINT `fk_piso_satisfaccion`
    FOREIGN KEY (`codigo-piso`)
    REFERENCES `inmobiliario`.`piso` (`codigo-piso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caracteristica_satisfaccion`
    FOREIGN KEY (`codigo-caracteristica`)
    REFERENCES `inmobiliario`.`caracteristica` (`codigo-caracteristica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliario`.`limitrofe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inmobiliario`.`limitrofe` (
  `nombre-pobl` VARCHAR(45) NOT NULL,
  `nombre-zona` VARCHAR(45) NOT NULL,
  `nombre-pobl-lim` VARCHAR(45) NOT NULL,
  `nombre-zona-lim` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre-pobl`, `nombre-zona`, `nombre-pobl-lim`, `nombre-zona-lim`),
  UNIQUE INDEX `nombre-pobl_UNIQUE` (`nombre-pobl` ASC) VISIBLE,
  UNIQUE INDEX `nombre-zona_UNIQUE` (`nombre-zona` ASC) VISIBLE,
  UNIQUE INDEX `nombre-pobl-lim_UNIQUE` (`nombre-pobl-lim` ASC) VISIBLE,
  UNIQUE INDEX `nombre-zona-lim_UNIQUE` (`nombre-zona-lim` ASC) VISIBLE,
  CONSTRAINT `fk_zona_limitrofe`
    FOREIGN KEY (`nombre-pobl` , `nombre-zona` , `nombre-pobl-lim` , `nombre-zona-lim`)
    REFERENCES `inmobiliario`.`zona` (`nombre-pobl` , `nombre-zona` , `nombre-pobl` , `nombre-zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inmobiliario`.`propiedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inmobiliario`.`propiedad` (
  `codigo-piso` INT NOT NULL,
  `codigo-persona` INT NOT NULL,
  PRIMARY KEY (`codigo-piso`, `codigo-persona`),
  UNIQUE INDEX `codigo-piso_UNIQUE` (`codigo-piso` ASC) VISIBLE,
  UNIQUE INDEX `codigo-persona_UNIQUE` (`codigo-persona` ASC) VISIBLE,
  CONSTRAINT `fk_piso_propiedad`
    FOREIGN KEY (`codigo-piso`)
    REFERENCES `inmobiliario`.`piso` (`codigo-piso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_propietario_propiedad`
    FOREIGN KEY (`codigo-persona`)
    REFERENCES `inmobiliario`.`propietario` (`codigo-persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
